from __future__ import annotations

import asyncio
import os
import uuid

import xenevis

from translator_bot.languages import language_buttons, language_label, normalize_language
from translator_bot.popup_alerts import install_popup_alert_patch, set_callback_alert
from translator_bot.profiles import get_user_language, set_user_language
from translator_bot.telegram_extract import (
    callback_data,
    current_chat_id,
    current_message_id,
    reply_to_message,
    text_from_message,
    user_snapshot,
)
from translator_bot.translator import build_translator_from_env, format_translation


PENDING_TTL_SECONDS = 10 * 60
PENDING_SETUP_ONLY = "__language_setup_only__"

# Load .env before creating Google Sheets, Vertex clients, and Telegram patch config.
xenevis.env.load(".env", required=False)

# Experimental: enable Telegram callback popup alerts for inline button clicks.
install_popup_alert_patch()

xenevis.configure(
    observer=xenevis.observer.console(format="native"),
    data=xenevis.data.google_sheets(),
)

translator = build_translator_from_env()


def vertex_timeout_seconds() -> float:
    raw = os.getenv("VERTEX_TIMEOUT_SECONDS", "30").strip()
    try:
        value = float(raw)
    except ValueError:
        return 30.0

    return max(5.0, value)


def looks_like_noise(text: str) -> bool:
    compact = text.strip().lower()
    return (
        not compact
        or compact in {"ok", "okej", "xd", "gg", "+", "?", "??", "lol", "lmao"}
        or len(compact) <= 2
    )


async def create_pending(ctx, payload: dict) -> str:
    token = uuid.uuid4().hex[:12]
    await ctx.cache.set(
        f"translator.pending.{token}",
        payload,
        ttl_seconds=PENDING_TTL_SECONDS,
    )
    return token


async def get_pending(ctx, token: str) -> dict | None:
    item = await ctx.cache.get(f"translator.pending.{token}")
    return item if isinstance(item, dict) else None


async def delete_pending(ctx, token: str) -> None:
    await ctx.cache.delete(f"translator.pending.{token}")


async def language_setup_output(
    ctx,
    *,
    chat_id: str | int,
    source_message_id: str | int,
    source_text: str,
):
    user = user_snapshot(ctx)

    token = await create_pending(
        ctx,
        {
            "chat_id": str(chat_id),
            "user_id": user["user_id"],
            "username": user["username"],
            "first_name": user["first_name"],
            "source_message_id": str(source_message_id),
            "source_text": source_text,
        },
    )

    return xenevis.telegram.reply_to(
        source_message_id,
        "First use: choose your translation language:",
        inline=language_buttons(xenevis, token),
    )


async def translate_text(text: str, target_language: str) -> tuple[str, bool, str]:
    timeout = vertex_timeout_seconds()

    try:
        result = await asyncio.wait_for(
            translator.translate(text, target_language=target_language),
            timeout=timeout,
        )
        return format_translation(result), True, "translated"

    except asyncio.TimeoutError:
        print(f"[vertex] translation timed out after {timeout:.0f}s")
        return (
            "Vertex AI translation timed out.\n"
            f"Timeout: {timeout:.0f}s\n\n"
            "Try again in a moment or increase VERTEX_TIMEOUT_SECONDS in .env.",
            False,
            "timeout",
        )

    except Exception as exc:
        print(f"[vertex] translation failed: {type(exc).__name__}: {exc}")

        message = str(exc)
        if "429" in message or "RESOURCE_EXHAUSTED" in message:
            status = "quota"
        else:
            status = "failed"

        return (
            "Vertex AI translation failed.\n"
            f"{type(exc).__name__}: {exc}\n\n"
            "Check GOOGLE_CLOUD_PROJECT / GOOGLE_CLOUD_LOCATION / VERTEX_MODEL "
            "and service account permissions.",
            False,
            status,
        )


def callback_alert_for_status(status: str) -> tuple[str, bool]:
    if status == "translated":
        return "Translation ready.", False

    if status == "timeout":
        return "Vertex AI timed out. Try again in a moment.", True

    if status == "quota":
        return "Vertex AI quota/rate limit hit. Try again later.", True

    return "Vertex AI translation failed.", True


@xenevis.telegram.command("help")
async def help_command(ctx):
    return xenevis.telegram.reply(
        "Translator bot\n\n"
        "Reply to a message with /tr to translate it.\n"
        "Use /mylang to set or change your language.\n"
        "Translations are generated by Vertex AI."
    )


@xenevis.telegram.command("mylang")
async def mylang_command(ctx):
    chat_id = current_chat_id(ctx)
    message_id = current_message_id(ctx)

    if chat_id is None or message_id is None:
        return xenevis.telegram.reply("I cannot detect this chat/message.")

    return await language_setup_output(
        ctx,
        chat_id=chat_id,
        source_message_id=message_id,
        source_text=PENDING_SETUP_ONLY,
    )


@xenevis.telegram.command("TR")
@xenevis.telegram.command("Tr")
@xenevis.telegram.command("tr")
async def translate_command(ctx):
    chat_id = current_chat_id(ctx)
    trigger_message_id = current_message_id(ctx)
    user = user_snapshot(ctx)

    if chat_id is None or trigger_message_id is None:
        return xenevis.telegram.reply("I cannot detect this chat/message.")

    reply = reply_to_message(ctx)

    if not reply:
        return xenevis.telegram.reply_to(
            trigger_message_id,
            "Reply to a message with /tr.",
        )

    source_message_id = reply.get("message_id")
    source_text = text_from_message(reply)

    if source_message_id is None or not source_text:
        return xenevis.telegram.reply_to(
            trigger_message_id,
            "I can only translate text/caption messages.",
        )

    if looks_like_noise(source_text):
        return xenevis.telegram.reply_to(
            source_message_id,
            "This message is too short/noisy to translate.",
        )

    language = await get_user_language(
        ctx,
        chat_id=chat_id,
        user_id=user["user_id"],
    )

    if not language:
        return await language_setup_output(
            ctx,
            chat_id=chat_id,
            source_message_id=source_message_id,
            source_text=source_text,
        )

    rendered, _ok, _status = await translate_text(source_text, language)

    return xenevis.telegram.reply_to(
        source_message_id,
        rendered,
    )


# Temporary generic callback router.
# SDK currently uses exact callback action matching, so dynamic callback data like
# tr_setup:<token>:pl is best handled here until callback prefix routing exists.
@xenevis.entry("telegram.callback", surface="telegram")
async def callback_router(ctx):
    data = callback_data(ctx)

    if not data or not data.startswith("tr_setup:"):
        set_callback_alert(ctx, "Unknown button.", show_alert=True)
        return None

    try:
        _prefix, token, language = data.split(":", 2)
    except ValueError:
        set_callback_alert(ctx, "Invalid setup token.", show_alert=True)
        return xenevis.telegram.edit("Invalid setup token.")

    pending = await get_pending(ctx, token)

    if pending is None:
        set_callback_alert(ctx, "This setup expired.", show_alert=True)
        return xenevis.telegram.edit("This setup expired. Try again with /tr or /mylang.")

    clicked_user = user_snapshot(ctx)
    expected_user_id = str(pending.get("user_id") or "")

    if clicked_user["user_id"] != expected_user_id:
        set_callback_alert(ctx, "This setup belongs to another user.", show_alert=True)
        return xenevis.telegram.edit("This language setup belongs to another user.")

    chat_id = pending.get("chat_id")
    source_message_id = pending.get("source_message_id")
    source_text = pending.get("source_text")
    target_language = normalize_language(language)

    await set_user_language(
        ctx,
        chat_id=chat_id,
        user_id=clicked_user["user_id"],
        language=target_language,
        username=clicked_user["username"],
        first_name=clicked_user["first_name"],
    )

    await delete_pending(ctx, token)

    if source_text == PENDING_SETUP_ONLY:
        set_callback_alert(ctx, f"Language saved: {language_label(target_language)}", show_alert=False)
        return xenevis.telegram.edit(
            f"Translation language saved: {language_label(target_language)}"
        )

    if not source_text or source_message_id is None:
        set_callback_alert(ctx, f"Language saved: {language_label(target_language)}", show_alert=False)
        return xenevis.telegram.edit(
            f"Translation language saved: {language_label(target_language)}"
        )

    rendered, ok, status = await translate_text(str(source_text), target_language)
    alert_text, show_alert = callback_alert_for_status(status)
    set_callback_alert(ctx, alert_text, show_alert=show_alert)

    # Edit the language selector message into the real Vertex AI translation or error.
    return xenevis.telegram.edit(rendered)


if __name__ == "__main__":
    print("Starting Xenevis Telegram Translator Bot — Vertex AI + callback popup alerts...")
    print("Translator provider: vertex")
    print(f"Vertex timeout: {vertex_timeout_seconds():.0f}s")
    print(f"Callback popup show_alert default: {os.getenv('TELEGRAM_CALLBACK_SHOW_ALERT', 'true')}")
    print("Use: reply to a message with /tr")
    xenevis.telegram.polling(
        allowed_updates=("message", "callback_query"),
    ).run()
